// frontend-svelte/src/pages/Login.svelte
<script lang="ts">
  import { auth } from '$lib/stores/auth';
  import { navigate } from '$app/navigation';
  import EloButton from "$lib/components/EloButton.svelte";
  import EloTextInput from "$lib/components/EloTextInput.svelte";

  let email = '';
  let password = '';
  let error = '';
  let loading = false;
  let validationError = '';

  function isValid(value: string) : boolean {
      if (!value) return false;

      return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
  }

  async function handleLogin(e: Event) {
    e.preventDefault();
    error = '';
    validationError = '';

    if (!isValid(email)) {
      validationError = 'Please enter a valid email address';
      return;
    }
    if (!password) {
      validationError = 'Please enter your password';
      return;
    }

    loading = true;

    try {
      await auth.login(email, password);
      navigate('/');
    } catch (err: any) {
      error = err.message || 'Login failed';
    } finally {
      loading = false;
    }
  }

  function handleGoogleLogin() {
    auth.loginWithGoogle();
  }
</script>

<div class="min-h-screen flex items-center justify-center bg-elo-primary-100 p-4">
  <div class="max-w-md w-full p-8 bg-white shadow-2xl z-10 rounded-xl">
    <div>
      <h2 class="text-center text-3xl font-medium text-elo-primary-700">Log in to Elotify</h2>
    </div>

    <form class="mt-8 space-y-6" on:submit={handleLogin} novalidate>
      {#if error || validationError}
        <div class="bg-elo-danger-100 border-l-4 border-elo-danger-500 text-elo-danger-700 px-4 py-3 rounded">
          <p class="font-medium">{error || validationError}</p>
        </div>
      {/if}

      <div class="space-y-4">
          <EloTextInput
                  type="email"
                  label="Email"
                  bind:value={email}/>

          <EloTextInput
                  label="Password"
                  type="password"
                  bind:value={password}
          />
      </div>

      <div class="flex items-center justify-center">
        <EloButton disabled={loading} type="submit">
          {loading ? 'Login in...' : 'Log in'}
        </EloButton>
      </div>

      <div class="relative">
        <div class="absolute inset-0 flex items-center">
          <div class="w-full border-t border-gray-300"></div>
        </div>
        <div class="relative flex justify-center text-sm">
          <span class="px-2 bg-white text-gray-500">Or continue with</span>
        </div>
      </div>

      <div class="flex items-center justify-center">
        <EloButton
                variant="secondary"
                type="button"
                on:click={handleGoogleLogin}>
          <svg class="w-5 h-5" viewBox="0 0 24 24">
            <path
              fill="#4285F4"
              d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
            />
            <path
              fill="#34A853"
              d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
            />
            <path
              fill="#FBBC05"
              d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
            />
            <path
              fill="#EA4335"
              d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
            />
          </svg>
          Log in with Google
        </EloButton>
      </div>

      <div class="text-center text-sm">
        <span class="text-gray-600">Don't have an account? </span>
        <a href="/register" class="font-medium text-elo-primary-600 hover:text-elo-primary-500 underline">
          Sign up
        </a>
      </div>
    </form>
  </div>
</div>

// app/login/page.tsx
'use client'

import { signIn } from 'next-auth/react'

export default function LoginPage() {

  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-100 font-sans">
      <div className="bg-white p-8 rounded-lg shadow-md w-full max-w-md text-center">
        <h1 className="mb-2 text-2xl">
          Welcome to Elo App
        </h1>
        <p className="text-gray-600 mb-8 text-sm">
          Sign in with your Google account to continue
        </p>

        <button
          onClick={() => signIn('google', { callbackUrl: '/' })}
          className="w-full py-3 bg-white text-gray-700 border border-gray-300 rounded text-base font-medium cursor-pointer flex items-center justify-center gap-2 transition-shadow hover:shadow-lg"
        >
          <svg width="18" height="18" viewBox="0 0 18 18">
            <path fill="#4285F4" d="M17.64 9.2c0-.637-.057-1.251-.164-1.84H9v3.481h4.844c-.209 1.125-.843 2.078-1.796 2.717v2.258h2.908c1.702-1.567 2.684-3.874 2.684-6.615z"/>
            <path fill="#34A853" d="M9 18c2.43 0 4.467-.806 5.956-2.184l-2.908-2.258c-.806.54-1.837.86-3.048.86-2.344 0-4.328-1.584-5.036-3.711H.957v2.332C2.438 15.983 5.482 18 9 18z"/>
            <path fill="#FBBC05" d="M3.964 10.707c-.18-.54-.282-1.117-.282-1.707s.102-1.167.282-1.707V4.961H.957C.347 6.175 0 7.55 0 9s.348 2.825.957 4.039l3.007-2.332z"/>
            <path fill="#EA4335" d="M9 3.58c1.321 0 2.508.454 3.44 1.345l2.582-2.58C13.463.891 11.426 0 9 0 5.482 0 2.438 2.017.957 4.961L3.964 7.29C4.672 5.163 6.656 3.58 9 3.58z"/>
          </svg>
          Sign in with Google
        </button>
      </div>
    </div>
  )
}
