// frontend-svelte/src/pages/Login.svelte
<script lang="ts">
  import { auth } from '$lib/stores/auth';
  import { navigate } from '$app/navigation';
  import EloButton from "$lib/components/EloButton.svelte";
  import EloTextInput from "$lib/components/EloTextInput.svelte";

  let email = '';
  let password = '';
  let error = '';
  let loading = false;
  let validationError = '';

  function isValid(value: string) : boolean {
      if (!value) return false;

      return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
  }

  async function handleLogin(e: Event) {
    e.preventDefault();
    error = '';
    validationError = '';

    if (!isValid(email)) {
      validationError = 'Please enter a valid email address';
      return;
    }
    if (!password) {
      validationError = 'Please enter your password';
      return;
    }

    loading = true;

    try {
      await auth.login(email, password);
      navigate('/');
    } catch (err: any) {
      error = err.message || 'Login failed';
    } finally {
      loading = false;
    }
  }

  function handleGoogleLogin() {
    auth.loginWithGoogle();
  }
</script>

<div class="min-h-screen flex items-center justify-center bg-elo-primary-100 p-4">
  <div class="max-w-md w-full p-8 bg-white shadow-2xl z-10 rounded-xl">
    <div>
      <h2 class="text-center text-3xl font-medium text-elo-primary-700">Log in to Elotify</h2>
    </div>

    <form class="mt-8 space-y-6" on:submit={handleLogin} novalidate>
      {#if error || validationError}
        <div class="bg-elo-danger-100 border-l-4 border-elo-danger-500 text-elo-danger-700 px-4 py-3 rounded">
          <p class="font-medium">{error || validationError}</p>
        </div>
      {/if}

      <div class="space-y-4">
          <EloTextInput
                  type="email"
                  label="Email"
                  bind:value={email}/>

          <EloTextInput
                  label="Password"
                  type="password"
                  bind:value={password}
          />
      </div>

      <div class="flex items-center justify-center">
        <EloButton disabled={loading} type="submit">
          {loading ? 'Login in...' : 'Log in'}
        </EloButton>
      </div>

      <div class="relative">
        <div class="absolute inset-0 flex items-center">
          <div class="w-full border-t border-gray-300"></div>
        </div>
        <div class="relative flex justify-center text-sm">
          <span class="px-2 bg-white text-gray-500">Or continue with</span>
        </div>
      </div>

      <div class="flex items-center justify-center">
        <EloButton
                variant="secondary"
                type="button"
                on:click={handleGoogleLogin}>
          <svg class="w-5 h-5" viewBox="0 0 24 24">
            <path
              fill="#4285F4"
              d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
            />
            <path
              fill="#34A853"
              d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
            />
            <path
              fill="#FBBC05"
              d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
            />
            <path
              fill="#EA4335"
              d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
            />
          </svg>
          Log in with Google
        </EloButton>
      </div>

      <div class="text-center text-sm">
        <span class="text-gray-600">Don't have an account? </span>
        <a href="/register" class="font-medium text-elo-primary-600 hover:text-elo-primary-500 underline">
          Sign up
        </a>
      </div>
    </form>
  </div>
</div>

// frontend/src/pages/Login.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';

export default function Login() {
  const navigate = useNavigate();
  const { login } = useAuth();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    try {
      // TODO: Replace with your actual authentication logic
      await login(email, password);
      navigate('/');
    } catch (err) {
      setError('Invalid credentials');
      console.error('Login error:', err);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-50">
      <div className="w-full max-w-md p-8 bg-white rounded-lg shadow-md">
        <h1 className="text-3xl font-bold text-center mb-6">Sign In</h1>

        {error && (
          <div className="mb-4 p-3 bg-red-100 text-red-700 rounded">
            {error}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium mb-1">Email</label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              className="w-full px-3 py-2 border rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="your@email.com"
            />
          </div>

          <div>
            <label className="block text-sm font-medium mb-1">Password</label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              className="w-full px-3 py-2 border rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="••••••••"
            />
          </div>

          <button
            type="submit"
            className="w-full px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 transition-colors font-medium"
          >
            Sign In
          </button>
        </form>

        <p className="mt-6 text-center text-sm text-gray-600">
          Don't have an account?{' '}
          <button
            onClick={() => navigate('/register')}
            className="text-blue-500 hover:text-blue-600 font-medium"
          >
            Sign up
          </button>
        </p>
      </div>
    </div>
  );
}
