// frontend-svelte/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { initRouter, getCurrentPath, matchRoute, type Route } from './lib/router.svelte';
  import Home from './pages/Home.svelte';
  import Login from './pages/Login.svelte';
  import Register from './pages/Register.svelte';
  import AuthCallback from './pages/AuthCallback.svelte';

  const routes: Route[] = [
    { path: '/', component: Home },
    { path: '/login', component: Login },
    { path: '/register', component: Register },
    { path: '/auth/callback', component: AuthCallback }
  ];

  onMount(() => {
    initRouter();
  });

  let Component = $derived(matchRoute(routes));
</script>

{#if Component}
  <Component />
{/if}

// frontend/src/App.tsx
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import { AuthProvider } from './contexts/AuthContext';
import Home from './pages/Home';
import Login from './pages/Login';
import Leagues from './pages/Leagues';
import './App.css';

function App() {
  return (
    <AuthProvider>
      <Router>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/login" element={<Login />} />
          <Route path="/leagues" element={<Leagues />} />
        </Routes>
      </Router>
    </AuthProvider>
  );
}

export default App;
